---
- name: Manage Azure network security groups
  azure.azcollection.azure_rm_securitygroup:
    resource_group: "{{ item.resource_group }}"
    name: "{{ item.name }}"
    location: "{{ item.location | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    tags: "{{ item.tags | default(omit) }}"
    append_tags: "{{ item.append_tags | default(true) }}"
    default_rules: "{{ item.default_rules | default(omit) }}"
    purge_default_rules: "{{ item.purge_default_rules | default(false) }}"
    rules: "{{ item.rules | default(omit) }}"
    purge_rules: "{{ item.purge_rules | default(false) }}"
  loop: "{{ az_network_security_groups }}"
