---
- name: Manage Azure virtual machines
  azure.azcollection.azure_rm_virtualmachine:
    resource_group: "{{ item.resource_group }}"
    name: "{{ item.name }}"
    location: "{{ item.location | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    tags: "{{ item.tags | default(omit) }}"
    append_tags: "{{ item.append_tags | default(true) }}"
    accept_terms: "{{ item.accept_terms | default(false) }}"
    admin_username: "{{ item.admin_username if ((item.state is defined and item.state == 'present') or item.state is not defined) else omit }}"
    admin_password: "{{ item.admin_password if ((item.state is defined and item.state == 'present') or item.state is not defined)
                                              and ((item.os_type is defined and item.os_type == 'Windows')
                                            or (((item.os_type is defined and item.os_type == 'Linux') or item.os_type is not defined)
                                              and (item.ssh_password_enabled is defined and item.ssh_password_enabled)))
                                            else omit }}"
    allocated: "{{ item.allocated | default(true) }}"
    availability_set: "{{ item.availability_set | default(omit) }}"
    boot_diagnostics: "{{ item.boot_diagnostics | default(omit) }}"
    custom_data: "{{ item.custom_data | default(omit) }}"
    data_disks: "{{ item.data_disks | default(omit) }}"
    ephemeral_os_disk: "{{ item.ephemeral_os_disk | default(false) }}"
    eviction_policy: "{{ (item.eviction_policy | default('Deallocate')) if item.priority is defined and item.priority == 'Spot' else omit }}"
    generalized: "{{ item.generalized | default(false) }}"
    image: "{{ item.image if ((item.state is defined and item.state == 'present') or item.state is not defined) else omit }}"
    license_type: "{{ item.license_type | default(omit) }}"
    managed_disk_type: "{{ item.managed_disk_type | default(omit) }}"
    max_price: "{{ (item.max_price | default(-1)) if item.priority is defined and item.priority == 'Spot' else omit }}"
    network_interface_names: "{{ item.network_interface_names | default(omit) }}"
    open_ports: "{{ item.open_ports | default(omit) }}"
    os_disk_name: "{{ item.os_disk_name | default(omit) }}"
    os_disk_size_gb: "{{ item.os_disk_size_gb | default(omit) }}"
    os_type: "{{ item.os_type | default('Linux') }}"
    plan: "{{ item.plan | default(omit) }}"
    priority: "{{ item.priority | default('None') }}"
    public_ip_allocation_method: "{{ item.public_ip_allocation_method | default(omit) }}"
    remove_on_absent: "{{ item.remove_on_absent | default(['all']) }}"
    restarted: "{{ item.restarted | default(false) }}"
    short_hostname: "{{ item.short_hostname | default(item.name) }}"
    ssh_password_enabled: "{{ item.ssh_password_enabled | default(true) }}"
    ssh_public_keys: "{{ item.ssh_public_keys if (item.ssh_password_enabled is defined and not item.ssh_password_enabled) else omit }}"
    started: "{{ item.started | default(true) }}"
    storage_account_name: "{{ item.storage_account_name | default(omit) }}"
    storage_blob_name: "{{ item.storage_blob_name | default(item.name + '.vhd') }}"
    storage_container_name: "{{ item.storage_container_name | default('vhds') }}"
    subnet_name: "{{ item.subnet_name | default(omit) }}"
    virtual_network_name: "{{ item.virtual_network_name | default(omit) }}"
    virtual_network_resource_group: "{{ item.virtual_network_resource_group | default(omit) }}"
    vm_size: "{{ item.vm_size if ((item.state is defined and item.state == 'present') or item.state is not defined) else omit }}"
    zones: "{{ item.zones | default(omit) }}"
  loop: "{{ az_virtual_machines }}"
